from environment.dashboard import Dashboard

dash = Dashboard()

# Provide relative paths to folders containing training logs generated by the Dashboard module
dash.plot_rewards(
    ["Relative/Path/To/Logs/1", "Relative/Path/To/Logs/2", "Relative/Path/To/Logs/3"])
